function gui = initGUI(cfg)
% INITGUI - Initialize Live Gunshot Localization Dashboard & Control Center
%
% PURPOSE:
%   Creates a high-resolution dark-themed graphical dashboard featuring:
%   1. Real-time 6-channel oscilloscope waveform monitor
%   2. 360° Polar Acoustic Radar Compass with DOA vector & confidence arc
%   3. Continuous Spatial Likelihood Spectrum (GCC + SRP + Fused)
%   4. Digital HUD Telemetry Readouts (DOA, Confidence, Valid Pairs, Latency)
%   5. Interactive hardware & acquisition control buttons
%
% INPUT:
%   cfg - Configuration structure from config.m
%
% OUTPUT:
%   gui - Structure containing all figure handles, axes, and UI controls

    % Close existing instance if open
    existingFig = findall(0, 'Type', 'figure', 'Name', 'NI-6221 Gunshot Localization Dashboard');
    if ~isempty(existingFig)
        close(existingFig);
    end

    % 1. Create Main Window Figure
    gui = struct();
    gui.fig = figure( ...
        'Name', 'NI-6221 Gunshot Localization Dashboard', ...
        'NumberTitle', 'off', ...
        'Color', [0.05, 0.07, 0.10], ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.05, 0.90, 0.88], ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'DockControls', 'off');

    % State flags
    gui.isRunning      = true;
    gui.isPaused       = false;
    gui.historyList    = [];
    gui.eventCounter   = 0;
    gui.lastAngle      = NaN;
    gui.lastConfidence = 0.0;
    gui.cfg            = cfg;

    %% 2. Header & Banner Panel
    uicontrol(gui.fig, 'Style', 'text', ...
        'String', 'ACOUSTIC GUNSHOT LOCALIZATION & TRACKING SYSTEM', ...
        'Units', 'normalized', 'Position', [0.02, 0.94, 0.65, 0.045], ...
        'BackgroundColor', [0.05, 0.07, 0.10], 'ForegroundColor', [0.2, 0.8, 1.0], ...
        'FontSize', 15, 'FontWeight', 'bold', 'HorizontalAlignment', 'left');

    gui.statusLabel = uicontrol(gui.fig, 'Style', 'text', ...
        'String', '● STATUS: ARMED & MONITORING (40 kS/s)', ...
        'Units', 'normalized', 'Position', [0.68, 0.94, 0.30, 0.045], ...
        'BackgroundColor', [0.08, 0.14, 0.22], 'ForegroundColor', [0.2, 0.9, 0.4], ...
        'FontSize', 11, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    %% 3. Live 6-Channel Oscilloscope Waveform Panel (Top Left)
    uicontrol(gui.fig, 'Style', 'text', 'String', 'LIVE 6-CHANNEL MICROPHONE WAVEFORMS (AI0 : AI5)', ...
        'Units', 'normalized', 'Position', [0.02, 0.89, 0.48, 0.03], ...
        'BackgroundColor', [0.05, 0.07, 0.10], 'ForegroundColor', [0.7, 0.85, 1.0], ...
        'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'left');

    gui.axWaveforms = axes(gui.fig, 'Units', 'normalized', ...
        'Position', [0.03, 0.53, 0.46, 0.36], ...
        'Color', [0.07, 0.09, 0.13], ...
        'XColor', [0.4, 0.55, 0.7], 'YColor', [0.4, 0.55, 0.7], ...
        'GridColor', [0.15, 0.22, 0.32], 'GridAlpha', 0.6);
    grid(gui.axWaveforms, 'on');
    xlabel(gui.axWaveforms, 'Time (ms)', 'Color', [0.6, 0.75, 0.9], 'FontSize', 8);
    ylabel(gui.axWaveforms, 'Amplitude (V)', 'Color', [0.6, 0.75, 0.9], 'FontSize', 8);

    % Pre-create line objects for each channel for fast blitting
    hold(gui.axWaveforms, 'on');
    channelColors = [
        0.20, 0.80, 1.00;  % AI0 (M1) - Cyan
        1.00, 0.60, 0.10;  % AI1 (M2) - Amber
        0.30, 0.95, 0.40;  % AI2 (M3) - Lime Green
        1.00, 0.30, 0.50;  % AI3 (M4) - Pink
        0.75, 0.40, 1.00;  % AI4 (M5) - Purple
        1.00, 0.95, 0.20   % AI5 (M6) - Yellow
    ];
    gui.lineWaveforms = gobjects(cfg.numMics, 1);
    for m = 1:cfg.numMics
        gui.lineWaveforms(m) = plot(gui.axWaveforms, [0, 1], [0, 0], ...
            'Color', channelColors(m, :), 'LineWidth', 1.1, ...
            'DisplayName', sprintf('AI%d (M%d)', cfg.channels(m), m));
    end
    legend(gui.axWaveforms, 'Location', 'northeast', 'TextColor', [0.8, 0.9, 1.0], ...
        'Color', [0.08, 0.12, 0.18], 'EdgeColor', [0.2, 0.3, 0.4], 'FontSize', 7);
    hold(gui.axWaveforms, 'off');

    %% 4. Spatial Likelihood & Beamforming Profile (Bottom Left)
    uicontrol(gui.fig, 'Style', 'text', 'String', 'HYBRID SPATIAL SPECTRUM P(θ) = 0.6 GCC + 0.4 SRP', ...
        'Units', 'normalized', 'Position', [0.02, 0.47, 0.48, 0.03], ...
        'BackgroundColor', [0.05, 0.07, 0.10], 'ForegroundColor', [0.7, 0.85, 1.0], ...
        'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'left');

    gui.axSpectrum = axes(gui.fig, 'Units', 'normalized', ...
        'Position', [0.03, 0.11, 0.46, 0.35], ...
        'Color', [0.07, 0.09, 0.13], ...
        'XColor', [0.4, 0.55, 0.7], 'YColor', [0.4, 0.55, 0.7], ...
        'GridColor', [0.15, 0.22, 0.32], 'GridAlpha', 0.6);
    grid(gui.axSpectrum, 'on');
    xlim(gui.axSpectrum, [0, 360]);
    ylim(gui.axSpectrum, [0, 1.05]);
    gui.axSpectrum.XTick = 0:45:360;
    xlabel(gui.axSpectrum, 'Azimuth Angle θ (degrees)', 'Color', [0.6, 0.75, 0.9], 'FontSize', 8);
    ylabel(gui.axSpectrum, 'Normalized Power', 'Color', [0.6, 0.75, 0.9], 'FontSize', 8);

    hold(gui.axSpectrum, 'on');
    gui.lineGcc = plot(gui.axSpectrum, 0:359, zeros(360, 1), '--', ...
        'Color', [0.2, 0.7, 1.0, 0.6], 'LineWidth', 1.0, 'DisplayName', 'P_{GCC}(θ)');
    gui.lineSrp = plot(gui.axSpectrum, 0:359, zeros(360, 1), ':', ...
        'Color', [1.0, 0.7, 0.2, 0.6], 'LineWidth', 1.2, 'DisplayName', 'P_{SRP}(θ)');
    gui.lineFused = plot(gui.axSpectrum, 0:359, zeros(360, 1), '-', ...
        'Color', [0.1, 0.95, 0.4], 'LineWidth', 2.0, 'DisplayName', 'P_{Fused}(θ)');
    gui.linePeakMarker = plot(gui.axSpectrum, 0, 0, 'rv', ...
        'MarkerSize', 8, 'MarkerFaceColor', [1.0, 0.2, 0.2], 'DisplayName', 'Estimated DOA');
    legend(gui.axSpectrum, 'Location', 'northeast', 'TextColor', [0.8, 0.9, 1.0], ...
        'Color', [0.08, 0.12, 0.18], 'EdgeColor', [0.2, 0.3, 0.4], 'FontSize', 7);
    hold(gui.axSpectrum, 'off');

    %% 5. 360° Polar Acoustic Radar Compass (Top Right)
    uicontrol(gui.fig, 'Style', 'text', 'String', '360° POLAR ACOUSTIC RADAR COMPASS', ...
        'Units', 'normalized', 'Position', [0.52, 0.89, 0.46, 0.03], ...
        'BackgroundColor', [0.05, 0.07, 0.10], 'ForegroundColor', [0.7, 0.85, 1.0], ...
        'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'left');

    gui.axRadar = axes(gui.fig, 'Units', 'normalized', ...
        'Position', [0.52, 0.45, 0.45, 0.45], ...
        'Color', [0.07, 0.09, 0.13]);
    updateRadar(gui.axRadar, NaN, 0, cfg, []);

    %% 6. Telemetry HUD Cards (Bottom Right)
    telemetryPanel = uipanel(gui.fig, 'Units', 'normalized', ...
        'Position', [0.52, 0.09, 0.45, 0.35], ...
        'BackgroundColor', [0.08, 0.11, 0.16], ...
        'BorderColor', [0.18, 0.26, 0.38], 'BorderWidth', 1);

    % Card 1: Estimated Direction of Arrival
    uicontrol(telemetryPanel, 'Style', 'text', 'String', 'ESTIMATED BEARING (DOA)', ...
        'Units', 'normalized', 'Position', [0.04, 0.75, 0.44, 0.18], ...
        'BackgroundColor', [0.08, 0.11, 0.16], 'ForegroundColor', [0.6, 0.75, 0.9], ...
        'FontSize', 9, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
    gui.txtDOA = uicontrol(telemetryPanel, 'Style', 'text', 'String', '---.-°', ...
        'Units', 'normalized', 'Position', [0.04, 0.40, 0.44, 0.38], ...
        'BackgroundColor', [0.08, 0.11, 0.16], 'ForegroundColor', [0.2, 0.9, 0.4], ...
        'FontSize', 22, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    % Card 2: Confidence Indicator
    uicontrol(telemetryPanel, 'Style', 'text', 'String', 'CONFIDENCE SCORE', ...
        'Units', 'normalized', 'Position', [0.52, 0.75, 0.44, 0.18], ...
        'BackgroundColor', [0.08, 0.11, 0.16], 'ForegroundColor', [0.6, 0.75, 0.9], ...
        'FontSize', 9, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
    gui.txtConf = uicontrol(telemetryPanel, 'Style', 'text', 'String', '--.-%', ...
        'Units', 'normalized', 'Position', [0.52, 0.40, 0.44, 0.38], ...
        'BackgroundColor', [0.08, 0.11, 0.16], 'ForegroundColor', [0.2, 0.8, 1.0], ...
        'FontSize', 22, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    % Card 3: Valid Pairs & Latency Sub-Panel
    gui.txtDetails = uicontrol(telemetryPanel, 'Style', 'text', ...
        'String', sprintf("Valid Pairs: --/15  |  Latency: --.- ms  |  Events: 0  |  Device: %s", cfg.deviceName), ...
        'Units', 'normalized', 'Position', [0.04, 0.08, 0.92, 0.28], ...
        'BackgroundColor', [0.05, 0.08, 0.12], 'ForegroundColor', [0.7, 0.85, 1.0], ...
        'FontSize', 9, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

    %% 7. Bottom Control Buttons Bar
    btnPanel = uipanel(gui.fig, 'Units', 'normalized', ...
        'Position', [0.02, 0.01, 0.96, 0.06], ...
        'BackgroundColor', [0.05, 0.07, 0.10], ...
        'BorderType', 'none');

    gui.btnPause = uicontrol(btnPanel, 'Style', 'pushbutton', 'String', 'PAUSE ACQUISITION', ...
        'Units', 'normalized', 'Position', [0.01, 0.1, 0.22, 0.8], ...
        'BackgroundColor', [0.15, 0.25, 0.38], 'ForegroundColor', [1 1 1], ...
        'FontWeight', 'bold', 'FontSize', 9, ...
        'Callback', @(src, evt) togglePause(gui.fig));

    gui.btnSim = uicontrol(btnPanel, 'Style', 'pushbutton', ...
        'String', sprintf("MODE: %s", ternary(cfg.simulationMode, "SIMULATION", "LIVE DAQ")), ...
        'Units', 'normalized', 'Position', [0.25, 0.1, 0.22, 0.8], ...
        'BackgroundColor', [0.18, 0.28, 0.22], 'ForegroundColor', [0.3, 0.95, 0.5], ...
        'FontWeight', 'bold', 'FontSize', 9, ...
        'Callback', @(src, evt) toggleSimulationMode(gui.fig));

    gui.btnClear = uicontrol(btnPanel, 'Style', 'pushbutton', 'String', 'CLEAR HISTORY', ...
        'Units', 'normalized', 'Position', [0.49, 0.1, 0.22, 0.8], ...
        'BackgroundColor', [0.28, 0.20, 0.15], 'ForegroundColor', [1.0, 0.8, 0.4], ...
        'FontWeight', 'bold', 'FontSize', 9, ...
        'Callback', @(src, evt) clearHistory(gui.fig));

    gui.btnQuit = uicontrol(btnPanel, 'Style', 'pushbutton', 'String', 'STOP & QUIT', ...
        'Units', 'normalized', 'Position', [0.73, 0.1, 0.25, 0.8], ...
        'BackgroundColor', [0.45, 0.12, 0.15], 'ForegroundColor', [1 1 1], ...
        'FontWeight', 'bold', 'FontSize', 9, ...
        'Callback', @(src, evt) stopSystem(gui.fig));

    % Store GUI handles in figure UserData for callbacks
    set(gui.fig, 'UserData', gui);
    drawnow;
end

%% Callbacks
function togglePause(fig)
    gui = get(fig, 'UserData');
    gui.isPaused = ~gui.isPaused;
    if gui.isPaused
        set(gui.btnPause, 'String', 'RESUME ACQUISITION', 'BackgroundColor', [0.5, 0.35, 0.1]);
        set(gui.statusLabel, 'String', '❚❚ SYSTEM PAUSED', 'ForegroundColor', [1.0, 0.7, 0.2]);
    else
        set(gui.btnPause, 'String', 'PAUSE ACQUISITION', 'BackgroundColor', [0.15, 0.25, 0.38]);
        set(gui.statusLabel, 'String', '● STATUS: ARMED & MONITORING (40 kS/s)', 'ForegroundColor', [0.2, 0.9, 0.4]);
    end
    set(fig, 'UserData', gui);
end

function toggleSimulationMode(fig)
    gui = get(fig, 'UserData');
    gui.cfg.simulationMode = ~gui.cfg.simulationMode;
    if gui.cfg.simulationMode
        set(gui.btnSim, 'String', 'MODE: SIMULATION', 'BackgroundColor', [0.18, 0.28, 0.22], 'ForegroundColor', [0.3, 0.95, 0.5]);
    else
        set(gui.btnSim, 'String', 'MODE: LIVE DAQ', 'BackgroundColor', [0.28, 0.18, 0.22], 'ForegroundColor', [1.0, 0.6, 0.6]);
    end
    set(fig, 'UserData', gui);
end

function clearHistory(fig)
    gui = get(fig, 'UserData');
    gui.historyList = [];
    updateRadar(gui.axRadar, gui.lastAngle, gui.lastConfidence, gui.cfg, []);
    set(fig, 'UserData', gui);
end

function stopSystem(fig)
    gui = get(fig, 'UserData');
    gui.isRunning = false;
    set(gui.statusLabel, 'String', '■ SYSTEM SHUTDOWN', 'ForegroundColor', [1.0, 0.3, 0.3]);
    set(fig, 'UserData', gui);
end

function res = ternary(cond, valTrue, valFalse)
    if cond
        res = valTrue;
    else
        res = valFalse;
    end
end
